VAGRANFILE_API_VERSION = "2"
Vagrant.configure(VAGRANFILE_API_VERSION) do |config|
   config.vm.define "node-lb" do |nodelb|
     nodelb.vm.box = "bento/ubuntu-16.04"
     nodelb.vm.network "private_network", ip: "192.168.33.11"
     nodelb.vm.hostname = "node-lb"
     nodelb.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
   end
end